### ISSUE TITLE
Initial layer initialization

### ISSUE THREAD

**Issue by dabeschte** [lucidrains/siren-pytorch#1]
Hi!
I tried to train SirenNet, but with this implementation, it converges much slower and less accurate than with the original implementation from [the colab](https://github.com/vsitzmann/siren/blob/master/explore_siren.ipynb).
In their implementation, the initial layer uses a different weight initialization, but the same w_0.

**Comment by lucidrains** [comment]
@dabeschte Hi! I'm very sorry, but it appears I misunderstood the initialization :(. I believe I have the correct implementation up in the latest version `0.0.4` Would you be willing to try again to see how you fare?

**Comment by dabeschte** [comment]
Wow, that was quick!
And it also solved the problem. The net converges much faster now. Thanks!

**Comment by lucidrains** [comment]
@dabeschte thank you for reporting! would have mislead so many poor researchers :(
