### ISSUE TITLE
FEATURE REQUEST:: Can you add dropout to the SirenNet?

### ISSUE THREAD

**Issue by JohnLaMaster** [lucidrains/SIREN-pytorch#8]
Can you add an optional dropout input to the SirenNet class?

**Comment by lucidrains** [comment]
@JohnLaMaster sure! https://github.com/lucidrains/siren-pytorch/commit/3555d895b213d243e8aa4db1913d01154cdcdd6b

**Comment by lucidrains** [comment]
@JohnLaMaster what is the latest on research into Siren networks?
